name = "bug-tracker"
compatibility_date = "2024-02-19"
main = "src/worker.ts"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "bug-tracker-db"
database_id = "817eb7d5-20a4-4028-9adc-999452b84e38"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "bug-tracker-files"

[site]
bucket = "./dist"
